# Generated by Django 2.2.dev20180926065127 on 2019-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressurelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='created',
            field=models.DateField(default='2019-01-26'),
        ),
    ]
