# Generated by Django 2.2.dev20180926065127 on 2019-01-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressurelog', '0002_auto_20190126_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='created',
            field=models.DateField(default='2019-01-27'),
        ),
    ]
