# Generated by Django 2.2.dev20180926065127 on 2019-01-29 19:40

import bloodpressurelog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressurelog', '0003_auto_20190127_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='created',
            field=models.DateField(default='2019-01-29'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='topNumber',
            field=models.IntegerField(default=120, validators=[bloodpressurelog.models.validate_name]),
        ),
    ]
