# Generated by Django 2.2.dev20180926065127 on 2019-02-02 19:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressurelog', '0004_auto_20190129_2040'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bloodpressure',
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='created',
            field=models.DateField(default='2019-02-02'),
        ),
    ]
