# Generated by Django 2.2.dev20180926065127 on 2019-02-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressurelog', '0005_auto_20190202_2021'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bloodpressure',
            managers=[
            ],
        ),
    ]
