# Generated by Django 2.2.dev20180926065127 on 2019-02-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressurelog', '0008_auto_20190202_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressure',
            name='created_time',
            field=models.TimeField(default='18:55:48'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='created',
            field=models.DateField(default='2019-02-04'),
        ),
    ]
